"""added email to a user

Revision ID: 748828505273
Revises: 945533bcdc74
Create Date: 2020-07-08 11:37:53.734711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748828505273'
down_revision = '945533bcdc74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
